### ISSUE TITLE
无法点击确定

### ISSUE THREAD

**Issue by Fahaxikiii** [fdklgbh/L4D2-Mod-Manager#1]
![image](https://github.com/fdklgbh/L4D2-Mod-Manager/assets/93320886/509aa733-9ed6-491a-bd80-301e71d1706b)

**Comment by fdklgbh** [comment]
需要配置禁用mod的路径

**Comment by Fahaxikiii** [comment]
> 需要配置禁用mod的路径

![image](https://github.com/fdklgbh/L4D2-Mod-Manager/assets/93320886/e734dca4-a389-4491-bdce-46ac1d35bdee) 依旧不行

**Comment by fdklgbh** [comment]
方便发一下你的两个路径吗,我这试了下,是可行的

**Comment by fdklgbh** [comment]
确定按钮的规则是游戏路径下有'left4dead2/addons'以及'left4dead2/addons/workshop'

> 方便发一下你的两个路径吗,我这试了下,是可行的

**Comment by Fahaxikiii** [comment]
> 确定按钮的规则是游戏路径下有'left4dead2/addons'以及'left4dead2/addons/workshop'
> 
> > 方便发一下你的两个路径吗,我这试了下,是可行的

懂了，workshop是steam创意工坊下的吧，第三方模组直接扔addons文件夹了

**Comment by fdklgbh** [comment]
> > 确定按钮的规则是游戏路径下有'left4dead2/addons'以及'left4dead2/addons/workshop'
> > > 方便发一下你的两个路径吗,我这试了下,是可行的
> 
> 懂了，workshop是steam创意工坊下的吧，第三方模组直接扔addons文件夹了

是的,这里需要粗略判断是不是游戏的根目录,后续如果有其他功能需要求生之路里的文件的话,就可以不需要再配置,没问题的话,我这里就关掉了

**Comment by Fahaxikiii** [comment]
> > > 确定按钮的规则是游戏路径下有'left4dead2/addons'以及'left4dead2/addons/workshop'
> > > > 方便发一下你的两个路径吗,我这试了下,是可行的
> > 
> > 
> > 懂了，workshop是steam创意工坊下的吧，第三方模组直接扔addons文件夹了
> 
> 是的,这里需要粗略判断是不是游戏的根目录,后续如果有其他功能需要求生之路里的文件的话,就可以不需要再配置,没问题的话,我这里就关掉了

好的，感谢指导~

**Comment by fdklgbh** [comment]
没关系,那这个我就关掉了
